name: Unit Tests  # Название рабочего процесса

# Запуск процесса на событие pull_request для ветки main
on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest  # Запуск на последней версии Ubuntu

    steps:
      - uses: actions/checkout@v2  # Клонирование репозитория

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Установить версию Node.js 16

      - run: npm ci  # Установить зависимости

      - run: npm test  # Запуск unit-тестов
